Repository JamesPartsafas/ConcordiaCurriculumManager, pull requests merged in 2023-09, with the labels that each got.

#4 Create the backend using C#
  Server/.dockerignore
  Server/.editorconfig
  Server/.gitignore
  Server/ConcordiaCurriculumManager.sln
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/ConcordiaCurriculumManager.csproj
  Server/ConcordiaCurriculumManager/Controllers/AuthenticationController.cs
  Server/ConcordiaCurriculumManager/DTO/AuthenticationResponse.cs
  Server/ConcordiaCurriculumManager/DTO/LoginDTO.cs
  Server/ConcordiaCurriculumManager/DTO/RegisterDTO.cs
  Server/ConcordiaCurriculumManager/Migrations/20230916042207_InitMigration.Designer.cs
  Server/ConcordiaCurriculumManager/Migrations/20230916042207_InitMigration.cs
  Server/ConcordiaCurriculumManager/Migrations/CCMDbContextModelSnapshot.cs
  Server/ConcordiaCurriculumManager/Models/BaseModel.cs
  Server/ConcordiaCurriculumManager/Models/Role.cs
  Server/ConcordiaCurriculumManager/Models/User.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Properties/launchSettings.json
  Server/ConcordiaCurriculumManager/Repositories/DatabaseContext/CCMDbContext.cs
  Server/ConcordiaCurriculumManager/Repositories/UserRepository.cs
  Server/ConcordiaCurriculumManager/Security/AuthorizationPolicies.cs
  Server/ConcordiaCurriculumManager/Security/TokenValidation.cs
  Server/ConcordiaCurriculumManager/Services/CacheService.cs
  Server/ConcordiaCurriculumManager/Services/InputHasherService.cs
  Server/ConcordiaCurriculumManager/Services/UserAuthenticationService.cs
  Server/ConcordiaCurriculumManager/Settings/DatabaseSettings.cs
  Server/ConcordiaCurriculumManager/Settings/IdentitySettings.cs
  Server/ConcordiaCurriculumManager/Settings/SeedDatabase.cs
  Server/ConcordiaCurriculumManager/Swagger/LoginDTOExample.cs
  Server/ConcordiaCurriculumManager/Swagger/RegisterDTOExample.cs
  Server/ConcordiaCurriculumManager/appsettings.Development.json
  Server/ConcordiaCurriculumManager/appsettings.json
  Server/ConcordiaCurriculumManagerTest/ConcordiaCurriculumManagerTest.csproj
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/UserRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CacheServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/InputHashServiceTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/UserAuthenticationServiceTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/HttpContextUtil.cs
  Server/ConcordiaCurriculumManagerTest/Usings.cs
  Server/Dockerfile
  Server/README.md
Labels: Backend

#31 #30 Setup CI/CD Github Workflows
  .github/workflows/ci-cd.yml
Labels: initiation, task

#38 Add CORS policy to allow frontend connection #37
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Settings/CorsSettings.cs
  Server/ConcordiaCurriculumManager/appsettings.Development.json
  Server/ConcordiaCurriculumManager/appsettings.json
Labels: backend, task

#53 Write documentation #52
  CourseAdmin/MilestonesDocument.txt
  CourseAdmin/Mockup.txt
  CourseAdmin/ProjectDescription.txt
  CourseAdmin/README.md
  CourseAdmin/StakeholderLiability.txt
  README.md
Labels: documentation, task

#55 Setup Frontend testing infrastructure
  App/__tests__/Registration.test.tsx
  App/__tests__/__mocks__/image_mock.tsx
  App/jest.config.ts
  App/package-lock.json
  App/package.json
  App/src/shared/Header.tsx
  App/tsconfig.node.json
Labels: frontend, task
