Repository JamesPartsafas/ConcordiaCurriculumManager, pull requests merged in 2023-10, with the labels that each got.

#60 #59 Use application/json for registration API calls
  App/package-lock.json
  App/src/main.tsx
  App/src/services/auth.ts
  Server/ConcordiaCurriculumManager/Controllers/AuthenticationController.cs
  Server/ConcordiaCurriculumManager/DTO/LoginDTO.cs
  Server/ConcordiaCurriculumManager/DTO/RegisterDTO.cs
  Server/ConcordiaCurriculumManager/Services/UserAuthenticationService.cs
Labels: backend, frontend, general, refactoring

#49 Setup Groups (backend)
  .vs/slnx.sqlite
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
  Server/ConcordiaCurriculumManager/DTO/GroupCreateDTO.cs
  Server/ConcordiaCurriculumManager/DTO/GroupDTO.cs
  Server/ConcordiaCurriculumManager/DTO/UserDTO.cs
  Server/ConcordiaCurriculumManager/Models/Users/Group.cs
  Server/ConcordiaCurriculumManager/Models/Users/User.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Repositories/DatabaseContext/CCMDbContext.cs
  Server/ConcordiaCurriculumManager/Repositories/GroupRepository.cs
  Server/ConcordiaCurriculumManager/Services/GroupService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/GroupRepositoryTests.cs
Labels: backend, initiation

#80 #79 Write iteration 2 documentation
  CourseAdmin/DemoPresentation.txt
  CourseAdmin/MilestonesDocument.txt
  README.md
Labels: documentation, task

#73 Feature/dossiers page/#69
  App/.prettierrc.cjs
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/Login.tsx
  App/src/pages/Register.tsx
  App/src/pages/dossier/DossierModal.tsx
  App/src/pages/dossier/Dossiers.tsx
  App/src/services/dossier.ts
  App/src/shared/Header.tsx
Labels: frontend, initiation

#82 Added GetAllGroups to controller and service
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
  Server/ConcordiaCurriculumManager/Services/GroupService.cs
Labels: backend

#85 84 fix repeated requests crash
  App/package-lock.json
  Seeder/package-lock.json
  Server/ConcordiaCurriculumManager/Program.cs
Labels: bug, backend, general

#89 88 dossier details endpoint
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DossierDetailsDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, initiation, task

#95 System design: Fixed props for button component
  App/src/components/Button.tsx
  App/src/components/LoadingSpinner.tsx
  App/src/components/Select.tsx
  App/src/models/course.ts
  App/src/pages/AddCourse.tsx
  App/src/pages/ComponentsList.tsx
  App/src/services/course.ts
Labels: frontend, general, task

#94 minor fixes
  App/src/pages/dossier/DossierModal.tsx
  App/src/pages/dossier/Dossiers.tsx
  App/src/services/user.ts
Labels: frontend, general, task

#92 #91 Implement endpoints for a user to edit a dossier.
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/EditDossierDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, general, task

#97 Check if the state of the existing course is Accepted
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
Labels: bug, backend, initiation

#104 #90 deploy application
  .github/workflows/backend-pipeline.yml
  .github/workflows/frontend-pipeline.yml
  .github/workflows/seeder-pipeline.yml
  App/jest.config.ts
  App/tsconfig-test.json
  App/tsconfig.json
  Scripts/ApplyProdAppSettings.sh
  Server/ConcordiaCurriculumManager/Program.cs
Labels: DevOps

#103 #93 Implement endpoints for a user to delete a dossier.
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DeleteDossierDTO.cs
  Server/ConcordiaCurriculumManager/Properties/launchSettings.json
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, general, task

#108 #107 Mask HS256 Key Value
  .github/workflows/backend-pipeline.yml
  Server/ConcordiaCurriculumManager/Dockerfile
Labels: bug, task, DevOps

#111 Homepage and Navbar modifications
  App/src/App.tsx
  App/src/pages/Home.tsx
  App/src/shared/Header.tsx
Labels: frontend, general

#116 Fix exception caused in GroupController
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
Labels: bug

#109 add-course-browser-frontend
  App/package-lock.json
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/CourseBrowser.tsx
Labels: frontend

#118 #10 Implement logout
  App/jest.config.ts
  App/src/App.tsx
  App/src/components/Button.tsx
  App/src/pages/Home.tsx
  App/src/services/user.ts
  App/src/shared/Header.tsx
  App/src/utils/toastUtils.ts
  App/theme.d.ts
  App/theme.ts
  App/tsconfig-test.json
Labels: frontend, general

#114 #113 upload iteration 3 milestone document
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, general, task

#120 Manage group
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/ManageableGroups.tsx
  App/src/services/group.ts
Labels: frontend, group/role, task

#122 Updated theme.ts with new system design
  App/theme.ts
Labels: frontend, general, task

#129 #128 create get all users endpoint
  .github/workflows/backend-pipeline.yml
  Server/ConcordiaCurriculumManager/Controllers/UsersController.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Repositories/UserRepository.cs
  Server/ConcordiaCurriculumManager/Services/GroupService.cs
  Server/ConcordiaCurriculumManager/Services/UserService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/GroupRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/UserRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/GroupControllerTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/UsersControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/UserServiceTest.cs
Labels: backend, group/role, task

#133 Add loading icon on page load, and add toast icon on successful login
  App/__tests__/Login.test.tsx
  App/__tests__/Registration.test.tsx
  App/src/pages/Login.tsx
  App/src/pages/Register.tsx
Labels: frontend, general

#134 Added layout and logic for edit course page #123
  App/src/App.tsx
  App/src/components/Select.tsx
  App/src/constants.ts
  App/src/pages/EditCourse.tsx
Labels: frontend, initiation

#138 #137 Add Group and Group Master claims
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
  Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs
  Server/ConcordiaCurriculumManager/Security/Claims.cs
  Server/ConcordiaCurriculumManager/Services/UserAuthenticationService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/UserAuthenticationServiceTests.cs
Labels: backend, group/role, task

#147 #146 implement policy based auth
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/EditDossierDTO.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/UserRepository.cs
  Server/ConcordiaCurriculumManager/Security/AuthorizationPolicies.cs
  Server/ConcordiaCurriculumManager/Security/Claims.cs
  Server/ConcordiaCurriculumManager/Security/Policies.cs
  Server/ConcordiaCurriculumManager/Security/Requirements/GroupMasterOrAdminRequirement.cs
  Server/ConcordiaCurriculumManager/Security/Requirements/Handlers/AdminHandler.cs
  Server/ConcordiaCurriculumManager/Security/Requirements/Handlers/GroupMasterHandler.cs
  Server/ConcordiaCurriculumManager/Security/Requirements/Handlers/OwnerOfDossierHanlder.cs
  Server/ConcordiaCurriculumManager/Security/Requirements/OwnerOfDossierRequirement.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManager/Services/UserService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, general, refactoring

#148 #136 missing fields
  Seeder/src/types/Course.ts
  Seeder/src/types/CourseCourseComponent.ts
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/DTO/Courses/SupportingFileDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseCreationInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseCreationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseModificationInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseModificationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseCreationInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseCreationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseModificationInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseModificationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseRequestInitiationDTO.cs
  Server/ConcordiaCurriculumManager/Migrations/20231029015207_CreateSupportingFiles.Designer.cs
  Server/ConcordiaCurriculumManager/Migrations/20231029015207_CreateSupportingFiles.cs
  Server/ConcordiaCurriculumManager/Migrations/CCMDbContextModelSnapshot.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Course.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseComponent.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseCourseComponent.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseCreationRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseModificationRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/SupportingFile.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DatabaseContext/CCMDbContext.cs
  Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManager/Swagger/CourseCreationInitiationDTOExample.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/SupportingFileTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, initiation, task, refactoring
