Repository JamesPartsafas/ConcordiaCurriculumManager, pull requests merged in 2023-11, with the labels that each got.

#150 Get course data endpoint
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/DTO/Courses/CourseDataDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend, initiation, task

#152 #151 Add CourseReferences information
  Seeder/src/data/CourseReferences.json
  Seeder/src/index.ts
  Seeder/src/types/CourseReferences.ts
Labels: backend, initiation, task

#153 Implement endpoints to edit create course requests
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseInitiationBaseDataDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseRequestInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/EditCourseCreationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/EditCourseModificationRequestDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, initiation, task

#156 Implement endpoints to edit course modification request
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, initiation, task

#157 Implement endpoints to edit course creation requests
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend, initiation, task

#158 Implement endpoint to delete course modification requests
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend, initiation, task

#159 Implement frontend UI to create a course deletion request
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/DeleteCourse.tsx
  App/src/services/course.ts
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseDeletionInitiationDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend, frontend, initiation, task

#161 Add remove group
  App/favicon.png
  App/index.html
  App/src/App.tsx
  App/src/models/user.ts
  App/src/pages/Home.tsx
  App/src/pages/ManageableGroups.tsx
  App/src/pages/RemoveUserFromGroup.tsx
  App/src/pages/addUserToGroup.tsx
  App/src/services/auth.ts
  App/src/services/group.ts
  App/src/services/user.ts
  Server/ConcordiaCurriculumManager/DTO/UserDTO.cs
Labels: frontend, group/role, general

#163 Remove group and Group Master filter
  App/src/App.tsx
  App/src/pages/Home.tsx
  App/src/pages/ManageableGroups.tsx
  App/src/pages/RemoveUserFromGroup.tsx
  App/src/pages/addUserToGroup.tsx
  App/src/services/auth.ts
  Server/ConcordiaCurriculumManager/Controllers/UsersController.cs
  Server/ConcordiaCurriculumManager/Security/Requirements/Handlers/GroupMasterHandler.cs
Labels: frontend, group/role

#166 Removes user from group masters when removed from group
  Server/ConcordiaCurriculumManager/Repositories/GroupRepository.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/GroupRepositoryTests.cs
Labels: backend, group/role, task

#164 No longer allow admins to be added to groups
  Server/ConcordiaCurriculumManager/Repositories/GroupRepository.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/GroupRepositoryTests.cs
Labels: backend, group/role, task

#171 Feature/dossier details/#127
  App/src/App.tsx
  App/src/constants.ts
  App/src/models/course.ts
  App/src/models/dossier.ts
  App/src/pages/AddCourse.tsx
  App/src/pages/Login.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/pages/dossier/Dossiers.tsx
  App/src/services/auth.ts
  App/src/services/dossier.ts
  App/tsconfig.node.json
Labels: frontend, task, dossiers

#174 #127 small big fix
  App/src/pages/dossier/DossierDetails.tsx
Labels: bug, frontend, dossiers

#173 Adding frontend tests
  App/__tests__/AddUserToGroup.test.tsx
  App/__tests__/ManageableGroups.test.tsx
  App/__tests__/RemoveUserFromGroup.test.tsx
Labels: testing

#180 #179 Correctly use dossier ID when submitting course creation request
  App/src/pages/AddCourse.tsx
  App/src/pages/EditCourse.tsx
Labels: bug, initiation, task

#178 Add course deletion request into dossier details page
  App/src/constants.ts
  App/src/models/course.ts
  App/src/models/dossier.ts
  App/src/pages/DeleteCourse.tsx
  App/src/pages/dossier/DossierDetails.tsx
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DossierDetailsDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs
Labels: backend, frontend, initiation, task

#183 Feature/edit delete course creation requestion/#181
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/course.ts
Labels: frontend, task, dossiers

#188 #186 persist logs and use filters
  Scripts/ApplyProdAppSettings.sh
  Server/ConcordiaCurriculumManager/ConcordiaCurriculumManager.csproj
  Server/ConcordiaCurriculumManager/Controllers/AuthenticationController.cs
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
  Server/ConcordiaCurriculumManager/Controllers/UsersController.cs
  Server/ConcordiaCurriculumManager/Middleware/EnrichLogContextMiddleware.cs
  Server/ConcordiaCurriculumManager/Middleware/ExceptionFilter.cs
  Server/ConcordiaCurriculumManager/Middleware/Exceptions/BadRequestException.cs
  Server/ConcordiaCurriculumManager/Middleware/Exceptions/InvalidInputException.cs
  Server/ConcordiaCurriculumManager/Middleware/Exceptions/NotFoundException.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/GroupRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManager/Services/GroupService.cs
  Server/ConcordiaCurriculumManager/Services/UserAuthenticationService.cs
  Server/ConcordiaCurriculumManager/appsettings.Development.json
  Server/ConcordiaCurriculumManager/appsettings.json
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/GroupControllerTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/UsersControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/UserAuthenticationServiceTests.cs
Labels: backend, refactoring

#190 #189 post documentation
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, task

#192 #191 add comments
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/EditCourseCreationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/EditCourseModificationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/InputDTOs/CourseCreationInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/InputDTOs/CourseDeletionInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/InputDTOs/CourseModificationInitiationDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/InputDTOs/EditCourseCreationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/InputDTOs/EditCourseModificationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/OutputDTOs/CourseCreationRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/OutputDTOs/CourseDeletionRequestDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/OutputDTOs/CourseModificationRequestDTO.cs
  Server/ConcordiaCurriculumManager/Migrations/20231112153608_CreateRequestConflicts.Designer.cs
  Server/ConcordiaCurriculumManager/Migrations/20231112153608_CreateRequestConflicts.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Course.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseRequest.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManager/Swagger/CourseCreationInitiationDTOExample.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/CourseTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, initiation, task

#208 Fix get course data
  .github/workflows/seeder-pipeline.yml
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/DTO/Courses/CourseDataDTO.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseCourseComponent.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/SupportingFile.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/SupportingFileTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: bug, backend, task

#209 Add comment field and back button to course deletion page
  App/src/pages/DeleteCourse.tsx
Labels: frontend, initiation, task

#210 Implement endpoints to edit & delete a Course Deletion Request
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/InputDTOs/EditCourseDeletionRequestDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, task, dossiers

#216 created a delete alert component
  App/src/components/Button.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/course.ts
  App/src/shared/DeleteAlert.tsx
Labels: frontend, task, dossiers

#217 Get course creation request endpoint
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/OutputDTOs/CourseCreationRequestCourseDetailsDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
Labels: backend, initiation, task

#218 Get course modification request endpoint
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/OutputDTOs/CourseModificationRequestCourseDetailsDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
Labels: backend, initiation, task

#213 Add and Remove Group Master #212
  App/__tests__/AddGroupMaster.test.tsx
  App/__tests__/RemoveGroupMaster.test.tsx
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/AddGroupMaster.tsx
  App/src/pages/ManageableGroups.tsx
  App/src/pages/RemoveGroupMaster.tsx
  App/src/services/auth.ts
  App/src/services/group.ts
Labels: frontend, group/role

#221 Get course deletion request endpoint
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
Labels: backend, initiation, task

#223 Creating a group
  App/__tests__/CreateGroup.test.tsx
  App/src/App.tsx
  App/src/pages/CreateGroup.tsx
  App/src/pages/ManageableGroups.tsx
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
Labels: frontend, group/role, task

#228 Create frontend page to edit a course deletion request
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/DeleteCourseEdit.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/course.ts
Labels: frontend, initiation, task

#229 Created group datatype and added sample groups and users to seeder
  Seeder/src/data/Groups.json
  Seeder/src/data/Users.json
  Seeder/src/index.ts
  Seeder/src/types/Group.ts
Labels: backend, group/role

#187 Made touchups to the landing page and the header
  App/src/pages/Home.tsx
  App/src/pages/ManageableGroups.tsx
  App/src/shared/Header.tsx
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/OutputDTOs/CourseCreationRequestCourseDetailsDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/OutputDTOs/CourseModificationRequestCourseDetailsDTO.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseCourseComponent.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/SupportingFile.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/SupportingFileTest.cs
Labels: frontend, general, task

#231 #199 added navbar on all pages except login and register
  App/src/App.tsx
  App/src/pages/AddCourse.tsx
  App/src/pages/DeleteCourse.tsx
  App/src/pages/DeleteCourseEdit.tsx
  App/src/pages/EditCourse.tsx
  App/src/pages/Home.tsx
  App/src/shared/Header.tsx
Labels: frontend, general, task
