Repository JamesPartsafas/ConcordiaCurriculumManager, pull requests merged in 2023-12, with the labels that each got.

#227 #226 generate conflict message
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseRequest.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend, task, dossiers

#236 Post iteration 5 docs
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, general, task

#240 239 approve dossier
  Server/ConcordiaCurriculumManager/Controllers/DossierReviewController.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Course.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseCourseComponent.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseVersion.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseCreationRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseDeletionRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseModificationRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseRequestOnExistingCourse.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierReviewRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierReviewControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/CourseRequests/CourseCreationRequestTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/CourseRequests/CourseRequestOnExistingCourseTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/CourseTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/DossierTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, reviewal, task

#242 241 return dossier
  Server/ConcordiaCurriculumManager/Controllers/DossierReviewController.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/DossierReview/ApprovalStage.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierReviewControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/ApprovalStageTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/DossierTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, reviewal, task

#244 Create the Dossier Review Page
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/dossier/DossierReview.tsx
Labels: frontend, task, dossiers

#234 added a model to select a course from it to eidt #182
  App/src/models/course.ts
  App/src/pages/EditCourse.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/pages/dossier/EditCourseModal.tsx
  App/src/services/course.ts
Labels: frontend, task, dossiers

#252 Adding dossier tables
  App/src/components/DossierTable.tsx
  App/src/pages/addUserToGroup.tsx
  App/src/pages/dossier/Dossiers.tsx
  App/src/services/user.ts
Labels: frontend, general, dossiers

#254 #253 incorporate approval logic in owner policy
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs
  Server/ConcordiaCurriculumManager/Security/Requirements/Handlers/OwnerOfDossierHanlder.cs
Labels: backend, group/role, task, dossiers

#257 Implement endpoint to create a dossier report
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/OutputDTOs/CourseDeletionRequestDetailsDTO.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DossierReportDTO.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/DossierReview/DossierReport.cs
  Server/ConcordiaCurriculumManager/Properties/launchSettings.json
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, initiation, task

#261 Implement endpoint to get dossier required review
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, initiation, task

#249 Feautre/edit requests/#247
  App/src/App.tsx
  App/src/components/Select.tsx
  App/src/models/course.ts
  App/src/pages/AddCourse.tsx
  App/src/pages/EditCourse.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/course.ts
Labels: frontend, task, dossiers

#230 Fix/course browser/#168
  App/package-lock.json
  App/package.json
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/CourseBrowser.tsx
  App/src/pages/CourseDetails.tsx
Labels: frontend, general, task

#265 Dossiers to review page
  App/src/App.tsx
  App/src/components/DossierTable.tsx
  App/src/constants.ts
  App/src/pages/dossier/DossierToReview.tsx
  App/src/pages/dossier/Dossiers.tsx
  App/src/services/dossier.ts
  App/src/shared/Header.tsx
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
Labels: frontend, dossiers

#269 #268 post milestone document
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, general, task
