Repository JamesPartsafas/ConcordiaCurriculumManager, pull requests merged in 2024-02, with the labels that each got.

#383 Implement endpoint to initiate a course grouping request endpoint
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, task, curriculum

#384 Implement modal to display Approval History
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierHistoryModal.tsx
  App/src/pages/dossier/DossierReview.tsx
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DossierReview/ApprovalHistoryDTO.cs
Labels: frontend, reviewal, task

#388 #387 Add missing information to the course creation and modification …
  App/src/pages/AddCourse.tsx
  App/src/pages/dossier/DossierDetails.tsx
Labels: bug, frontend

#391 Upgraded Diff Viewer to detect string changes char by char #324
  App/package-lock.json
  App/package.json
  App/src/components/CourseDifference/CourseDiffViewer.tsx
  App/src/components/CourseDifference/NewStringDiff.tsx
  App/src/components/CourseDifference/OldStringDiff.tsx
  App/src/components/CoursePreviewWithChange.tsx
  App/src/components/VersionDifference.tsx
  App/src/models/course.ts
  App/src/pages/AddCourse.tsx
  App/src/pages/dossier/DossierReport.tsx
  App/src/utils/courseGetters.tsx
Labels: frontend, dossiers

#400 Search for curriculum by school
  App/src/App.tsx
  App/src/constants.ts
  App/src/models/courseGrouping.ts
  App/src/pages/CourseGroupingBySchool.tsx
  App/src/services/courseGrouping.ts
Labels: frontend, curriculum

#402 #401 Fix Crashing Seeder Pipeline
  Seeder/src/types/CourseGrouping.ts
Labels: bug, DevOps

#372 Feature/course grouping page/#365
  App/src/constants.ts
  App/src/pages/CourseGrouping.tsx
Labels: frontend, task, dossiers

#366 Fix/dossier report UI fixes
  App/src/assets/styles/print.css
  App/src/components/CourseDifference/CourseDiffViewer.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/pages/dossier/DossierReport.tsx
  App/src/shared/Header.tsx
Labels: frontend, task, dossiers

#405 #404 expand email notification
  Server/ConcordiaCurriculumManager/EmailTemplates.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierReviewRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManager/Services/EmailService.cs
  Server/ConcordiaCurriculumManager/Services/GroupService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
Labels: backend, notification, task

#390 Dossier browser
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/dossier/DossierBrowser.tsx
  App/src/pages/dossier/DossierToReview.tsx
  App/src/pages/dossier/Dossiers.tsx
  App/src/services/dossier.ts
Labels: frontend, dossiers

#398 Fixed Title overflow into description column
  App/src/components/DossierTable.tsx
Labels: bug, dossiers

#408 Created Change Log Component
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/dossier/DossierChangeLog.tsx
  App/src/pages/dossier/DossierReport.tsx
  App/src/services/dossier.ts
Labels: frontend, dossiers

#407 Display the groups that a user belong to #406 Added the user groups page
  App/src/App.tsx
  App/src/components/GroupTable.tsx
  App/src/constants.ts
  App/src/pages/Home.tsx
  App/src/pages/groups/myGroups.tsx
  App/src/shared/Header.tsx
Labels: frontend, group/role, task

#411 Post iteration 9 documentation
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, task

#414 #413 Create endpoint to initiate course grouping deletion request
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseGroupings/CourseGrouping.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseGroupingRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, task, curriculum

#417 Implement endpoint to edit a curriculum deletion request
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
Labels: backend, task, curriculum

#418 Implement endpoint to edit a curriculum creation request
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
Labels: backend, task, curriculum

#425 421 Ensure dossier consistency when creating requests
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/DossierTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: task, dossiers, curriculum

#428 Display the course grouping requests in the dossier review page
  App/src/models/courseGrouping.ts
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierReview.tsx
Labels: frontend, task, dossiers

#430 Initiate course grouping deletion request
  App/src/App.tsx
  App/src/constants.ts
  App/src/models/courseGrouping.ts
  App/src/pages/DeleteCourseGrouping.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/courseGrouping.ts
  Server/ConcordiaCurriculumManager/DTO/CourseGrouping/CourseGroupingDTO.cs
Labels: frontend, task, curriculum

#433 Create page to edit a course grouping deletion request.
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/DeleteCourseGroupingEdit.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/courseGrouping.ts
Labels: frontend, task, curriculum

#434 Implement button functionality to delete a course grouping deletion request
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/courseGrouping.ts
Labels: frontend, task, curriculum

#440 #439 Fix not accepted course groupings showing in search result
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseGroupingRepositoryTests.cs
Labels: bug, backend, curriculum

#438 Group Browser and Details page #437
  App/src/App.tsx
  App/src/components/GroupTable.tsx
  App/src/constants.ts
  App/src/pages/BrowserList.tsx
  App/src/pages/groups/GroupDetails.tsx
  App/src/pages/groups/allGroups.tsx
Labels: frontend, group/role

#442 Add Course publish button to change log courses
  App/src/pages/dossier/DossierChangeLog.tsx
  App/src/services/dossier.ts
  App/src/shared/Header.tsx
Labels: frontend, task, dossiers

#436 removed navigation buttons from the print page
  App/src/pages/dossier/DossierReport.tsx
Labels: frontend, task, dossiers

#445 Feature/grouping requests/#432
  App/src/App.tsx
  App/src/constants.ts
  App/src/models/courseGrouping.ts
  App/src/pages/courseGroupings/CourseGrouping.tsx
  App/src/pages/courseGroupings/CourseGroupingByName.tsx
  App/src/pages/courseGroupings/CourseGroupingBySchool.tsx
  App/src/pages/courseGroupings/CreateCourseGrouping.tsx
  App/src/pages/courseGroupings/DeleteCourseGrouping.tsx
  App/src/pages/courseGroupings/DeleteCourseGroupingEdit.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/courseGrouping.ts
Labels: frontend, task, dossiers, curriculum

#444 #443 publish course grouping
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseGroupings/CourseGrouping.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseGroupingRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
Labels: backend, task, curriculum

#447 Post iteration 10 documentation
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, task

#449 Add horizontal scroll bar for groups in the Discussion Board
  App/src/pages/dossier/DossierReview.tsx
Labels: frontend, reviewal, task, dossiers

#454 Allow course groupings to have their changes approved
  Server/ConcordiaCurriculumManager/Models/Curriculum/CourseGroupings/CourseGrouping.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseGroupingRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierReviewRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/DossierTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, reviewal, task, curriculum

#458 Return groupings in dossier report
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DossierReportDTO.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseGroupingRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/DossierReview/DossierReport.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, task, dossiers, curriculum

#457 Add date and time to the print output of dossier report and change log
  App/src/assets/styles/print.css
  App/src/pages/dossier/DossierChangeLog.tsx
  App/src/pages/dossier/DossierReport.tsx
Labels: frontend, task, dossiers

#461 Write endpoint to query grouping requests
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/CourseRequests/CourseGroupingRequests/CourseGroupingRequestDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
Labels: backend, task, curriculum

#464 Implement approved curriculum changes across all dossiers
  Server/ConcordiaCurriculumManager/DTO/Courses/CourseChangesDTO.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/DossierReview/CourseChanges.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, task, curriculum

#466 #465 use web socket
  App/__tests__/__mocks__/signalR_mock.tsx
  App/jest.config.ts
  App/package-lock.json
  App/package.json
  App/src/pages/dossier/DossierReview.tsx
  App/src/utils/SignalRManager.ts
  Server/ConcordiaCurriculumManager/Controllers/DossierReviewController.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Security/Requirements/Handlers/OwnerOfDossierHanlder.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManager/SignalR/DossierDiscussionSignalR.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/SignalR/DossierDiscussionSignalRTest.cs
Labels: enhancement, backend, frontend, 491-40114180
