Repository JamesPartsafas/ConcordiaCurriculumManager, pull requests merged in 2024-04, with the labels that each got.

#584 Prevent deletion of dossier requests
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
Labels: bug, backend, reviewal

#582 Implement reset password page
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/ResetPassword.tsx
  App/src/services/user.ts
Labels: frontend, general, task

#566 added delete alerts
  App/src/pages/courseGroupings/CreateCourseGrouping.tsx
Labels: frontend, task, dossiers

#573 Requested Fixes for frontend
  App/src/pages/courseGroupings/CourseGroupingByName.tsx
  App/src/pages/courseGroupings/CourseGroupingBySchool.tsx
  App/src/pages/dossier/DossierToReview.tsx
  App/src/pages/groups/AddGroupMaster.tsx
  App/src/pages/groups/GroupDetails.tsx
  App/src/pages/groups/ManageableGroups.tsx
  App/src/pages/groups/RemoveGroupMaster.tsx
  App/src/pages/groups/RemoveUserFromGroup.tsx
  App/src/pages/groups/addUserToGroup.tsx
Labels: bug, frontend

#580 Add Course Grouping to Change Log #533
  App/src/components/Dossiers/DossierReportCourseGrouping.tsx
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierChangeLog.tsx
  App/src/pages/dossier/DossierReport.tsx
  App/src/services/dossier.ts
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
Labels: frontend, dossiers

#579 Add Difference for course grouping to dossier report
  App/src/components/Dossiers/DossierReportCourseGrouping.tsx
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierReport.tsx
Labels: frontend, dossiers

#581 Metrics frontend
  App/__tests__/Metrics.test.tsx
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/BrowserList.tsx
  App/src/pages/Metrics.tsx
  App/src/services/metrics.ts
Labels: frontend, metrics

#585 closes Filter groupings by request type #577
  App/src/pages/dossier/DossierDetails.tsx
Labels: frontend

#587 Post documentation
  CourseAdmin/FinalPresentation.txt
  README.md
Labels: documentation, task
