Repository JamesPartsafas/ConcordiaCurriculumManager, pull requests merged in 2024-01, with the labels that each got.

#271 #270 Fix versioning for created courses
  Server/ConcordiaCurriculumManager/DTO/Courses/CourseDataDTO.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseCreationRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/CourseRequest.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/CourseRequests/CourseCreationRequestTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/CourseRequests/CourseRequestOnExistingCourseTest.cs
Labels: bug, backend, reviewal, task

#267 Added a confirmation button for group deletion
  App/src/pages/ManageableGroups.tsx
Labels: frontend, group/role, task

#273 Dossier review page
  App/src/models/dossier.ts
  App/src/pages/DeleteCourseEdit.tsx
  App/src/pages/dossier/DossierReview.tsx
  App/src/services/dossierreview.ts
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DossierReview/DossierDiscussionMessageDTO.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: frontend, task, dossiers

#280 Feature/approval pipeline/#263
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierDetails.tsx
  App/src/pages/dossier/Dossiers.tsx
  App/src/pages/dossier/EditApprovalStagesModal.tsx
  App/src/services/dossierReview.ts
Labels: frontend, task, dossiers

#278 Created a reusable course difference visualizer component
  App/src/components/CoursePreview.tsx
  App/src/components/CoursePreviewWithChange.tsx
  App/src/components/VersionDifference.tsx
  App/src/pages/AddCourse.tsx
Labels: frontend, general, task

#279 Styled 404 page
  App/src/index.css
  App/src/pages/NotFound.tsx
Labels: story, frontend, general

#288 #285 fix merge conflicts
  App/src/models/dossier.ts
Labels: bug, frontend

#287 Fix duplicate requests
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
Labels: bug, backend, task

#292 Dossiers to review page
  App/src/pages/dossier/DossierDetails.tsx
  App/src/pages/dossier/DossierToReview.tsx
  App/src/pages/dossier/Dossiers.tsx
Labels: frontend, dossiers

#293 Implement endpoint to get all changes across all dossiers
  Server/ConcordiaCurriculumManager/AutoMapperProfile.cs
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/DTO/Courses/CourseChangesDTO.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/DossierReview/CourseChanges.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, reviewal, task

#294 Implement "All Groups" tab in Discussion Board
  App/src/pages/dossier/DossierReview.tsx
Labels: frontend, task, dossiers

#299 a submitted dossier is uneditable except if a user is a current revie…
  App/src/pages/dossier/DossierDetails.tsx
Labels: frontend, task, dossiers

#301 fixed race condition bug #300
  App/src/App.tsx
  App/src/pages/Login.tsx
  App/src/shared/Header.tsx
Labels: bug, frontend

#296 worked on adding deleted stages to the UI #295
  App/src/pages/dossier/EditApprovalStagesModal.tsx
Labels: backend, frontend, task, dossiers

#248 Edit/Delete a group as admin or group master
  Server/ConcordiaCurriculumManager/ConcordiaCurriculumManager.csproj
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
  Server/ConcordiaCurriculumManager/Repositories/GroupRepository.cs
  Server/ConcordiaCurriculumManager/Services/GroupService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/GroupRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/GroupControllerTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/GroupServiceTest.cs
Labels: backend, group/role

#305 fixed button margins
  App/__tests__/AddGroupMaster.test.tsx
  App/__tests__/AddUserToGroup.test.tsx
  App/__tests__/CreateGroup.test.tsx
  App/__tests__/ManageableGroups.test.tsx
  App/__tests__/RemoveGroupMaster.test.tsx
  App/__tests__/RemoveUserFromGroup.test.tsx
  App/src/App.tsx
  App/src/pages/AddGroupMaster.tsx
  App/src/pages/Home.tsx
  App/src/pages/ManageableGroups.tsx
  App/src/pages/RemoveGroupMaster.tsx
  App/src/pages/RemoveUserFromGroup.tsx
  App/src/pages/addUserToGroup.tsx
  App/src/pages/dossier/DossierToReview.tsx
  App/src/pages/dossier/Dossiers.tsx
  App/src/pages/groups/AddGroupMaster.tsx
  App/src/pages/groups/CreateGroup.tsx
  App/src/pages/groups/ManageableGroups.tsx
  App/src/pages/groups/RemoveGroupMaster.tsx
  App/src/pages/groups/RemoveUserFromGroup.tsx
  App/src/pages/groups/addUserToGroup.tsx
Labels: bug, frontend

#307 #306 post iteration 7 documentation
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, task

#309 #308 send email on approval
  .github/workflows/backend-pipeline.yml
  Scripts/ApplyProdAppSettings.sh
  Server/ConcordiaCurriculumManager/ConcordiaCurriculumManager.csproj
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierReviewRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManager/Services/EmailService.cs
  Server/ConcordiaCurriculumManager/Settings/SenderEmailSettings.cs
  Server/ConcordiaCurriculumManager/appsettings.Development.json
  Server/ConcordiaCurriculumManager/appsettings.json
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
Labels: notification, task

#311 #310 Remove object selectors for course and role
  Server/ConcordiaCurriculumManager/Models/Curriculum/Course.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs
Labels: bug, backend, refactoring

#313 #312 Implement endpoint to get course groupings by school
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
Labels: backend, task, curriculum

#315 #314 search groupings
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
Labels: backend, task, curriculum

#318 #317 block deletion request
  App/src/pages/DeleteCourse.tsx
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: task, curriculum

#321 Some minor fixes for the Dossier review page
  App/src/pages/dossier/DossierReview.tsx
Labels: frontend, task, dossiers

#323 Important fix in initiating a course creation request
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseIdentifiersRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseIdentifiersRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: bug, backend, task, curriculum

#325 cannot edits course name and number of an existing course
  App/src/components/Select.tsx
  App/src/pages/AddCourse.tsx
Labels: frontend, task, dossiers

#328 Implement reply functionality with nested message system
  App/src/pages/dossier/DossierReview.tsx
Labels: frontend, task, dossiers

#330 Overflow fixes #282
  App/src/components/GroupTable.tsx
  App/src/pages/groups/ManageableGroups.tsx
Labels: story, frontend, general

#336 #335 fix backend ci/cd pipeline
  Scripts/ApplyProdAppSettings.sh
  Seeder/src/index.ts
  Server/ConcordiaCurriculumManager/Migrations/CCMDbContextModelSnapshot.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/appsettings.Development.json
Labels: bug, DevOps

#339 #335 improve error readability in ci/cd
  .github/workflows/seeder-pipeline.yml
  Scripts/ApplyProdAppSettings.sh
  Seeder/src/index.ts
  Server/ConcordiaCurriculumManager/Program.cs
Labels: bug, DevOps

#333 Dossiers to review page
  App/__tests__/Dossiers.test.tsx
  App/__tests__/DossiersToReview.test.tsx
  App/src/components/DossierTable.tsx
  App/src/constants.ts
  App/src/pages/dossier/DossierDetails.tsx
  App/src/pages/dossier/DossierReport.tsx
  App/src/pages/dossier/DossierReview.tsx
  App/src/pages/dossier/DossierToReview.tsx
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
Labels: frontend, testing, dossiers

#341 Bacckend fix for Reject Dossier
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/DossierTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
Labels: bug, backend, dossiers

#338 Deleting and editing groups #337 added delete/edit functions
  App/src/components/GroupTable.tsx
  App/src/pages/groups/ManageableGroups.tsx
  App/src/services/group.ts
Labels: frontend, group/role, task

#342 Fixed create/edit group to not allow empty names and added test
  Server/ConcordiaCurriculumManager/ConcordiaCurriculumManager.csproj
  Server/ConcordiaCurriculumManager/Controllers/GroupController.cs
  Server/ConcordiaCurriculumManager/DTO/GroupCreateDTO.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/GroupControllerTests.cs
Labels: backend, group/role

#344 Feature/course info page/#170
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/CourseDetails.tsx
  App/src/pages/NoData.tsx
  App/src/services/course.ts
  App/src/shared/Header.tsx
Labels: frontend, general, task

#346 Implemented Query Course By Id
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend

#348 Implemented GetCoursesBySubject and related tests
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend

#354 Made groups deletable only if they are in no approval stages
  Server/ConcordiaCurriculumManager/Repositories/GroupRepository.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/GroupRepositoryTests.cs
Labels: backend

#356 #355 show review user name in discussion board
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierReview.tsx
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DossierReview/DossierDiscussionMessageDTO.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, reviewal, task, dossiers

#353 Created Dossier Report page version 1 | Feat/dossier report/297
  App/__tests__/__mocks__/styleMock.js
  App/jest.config.ts
  App/src/App.tsx
  App/src/assets/styles/print.css
  App/src/components/VersionDifference.tsx
  App/src/constants.ts
  App/src/models/course.ts
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierDetails.tsx
  App/src/pages/dossier/DossierReport.tsx
  App/src/services/dossier.ts
Labels: frontend, task, dossiers

#359 #358 post documentation for iteration 8
  CourseAdmin/MilestonesDocument.txt
  CourseAdmin/SwaggerUI.pdf
Labels: documentation, task

#367 laid the foundation for course grouping. added necessary files #365
  App/src/App.tsx
  App/src/constants.ts
  App/src/models/course.ts
  App/src/models/courseGrouping.ts
  App/src/pages/CourseGrouping.tsx
  App/src/services/courseGrouping.ts
Labels: frontend, task

#370 Implement endpoint to publish a course
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Course.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/CourseControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Models/CourseTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, initiation, task

#375 #374 delete grouping request
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/Dossier.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
Labels: backend, task, curriculum

#380 Implement search dossier endpoint
  Server/ConcordiaCurriculumManager/Controllers/DossierController.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, initiation, task
