Repository JamesPartsafas/ConcordiaCurriculumManager, pull requests merged in 2024-03, with the labels that each got.

#468 Clean old table log entries
  .github/workflows/clean-logs.yml
  Scripts/CleanupLogs.sh
Labels: task, DevOps, curriculum

#463 Feature/grouping requests/#432
  App/src/components/CourseGrouping/SearchCourseGrouping.tsx
  App/src/constants.ts
  App/src/models/courseGrouping.ts
  App/src/pages/courseGroupings/CreateCourseGrouping.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/pages/dossier/SelectCourseModal.tsx
Labels: frontend, task, dossiers

#470 #469 Update Pipeline Dependencies
  .github/workflows/backend-pipeline.yml
  .github/workflows/clean-logs.yml
  .github/workflows/frontend-pipeline.yml
  .github/workflows/seeder-pipeline.yml
Labels: DevOps

#477 manageable groups page feeedback #474
  App/src/pages/groups/AddGroupMaster.tsx
  App/src/pages/groups/CreateGroup.tsx
  App/src/pages/groups/ManageableGroups.tsx
  App/src/pages/groups/RemoveGroupMaster.tsx
  App/src/pages/groups/RemoveUserFromGroup.tsx
  App/src/pages/groups/addUserToGroup.tsx
Labels: frontend, general

#476 dossier details fix #473
  App/src/pages/dossier/DossierDetails.tsx
Labels: frontend, general

#475 Styling group details page #472
  App/src/pages/groups/GroupDetails.tsx
Labels: frontend, general

#483 #482 Allow New Courses To Be Published
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/CourseRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend, reviewal, task

#485 Post iteration 11 documentation
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, task

#489 Write new developer instructions
  README.md
Labels: documentation, task

#487 Fix incorrect query
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
Labels: bug, backend, reviewal

#494 Implement endpoint to edit message
  Server/ConcordiaCurriculumManager/Controllers/DossierReviewController.cs
  Server/ConcordiaCurriculumManager/DTO/Dossiers/DossierReview/EditDossierDiscussionMessageDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/DatabaseContext/CCMDbContext.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierReviewRepository.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/DossierReviewRepositoryTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/DossierReviewControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, reviewal, task

#492 Update dossier groupings on dossier being accepted
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, reviewal, task, curriculum

#502 Implement frontend to edit a review message
  App/src/pages/dossier/DossierReview.tsx
  App/src/services/dossierreview.ts
Labels: frontend, reviewal, task

#512 #511 use longpolling as fallback
  App/src/pages/dossier/DossierReview.tsx
  App/src/utils/SignalRManager.ts
  Server/ConcordiaCurriculumManager/Security/Requirements/Handlers/OwnerOfDossierHanlder.cs
  Server/ConcordiaCurriculumManager/SignalR/DossierDiscussionSignalR.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/SignalR/DossierDiscussionSignalRTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/HttpContextUtil.cs
Labels: backend, reviewal, 491-40114180

#510 Requirements to fulfill program credits
  App/src/App.tsx
  App/src/components/CourseGroupingComponent.tsx
  App/src/constants.ts
  App/src/pages/CoursesLeft.tsx
Labels: story, task, 491-40153034

#495 491 daniel
  App/__tests__/EditProfileInfo.test.tsx
  App/__tests__/ProfilePage.test.tsx
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/EditProfileInfo.tsx
  App/src/pages/ProfilePage.tsx
  App/src/services/auth.ts
  App/src/shared/Header.tsx
  Server/ConcordiaCurriculumManager/Controllers/AuthenticationController.cs
  Server/ConcordiaCurriculumManager/Repositories/UserRepository.cs
  Server/ConcordiaCurriculumManager/Services/UserAuthenticationService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/UserAuthenticationServiceTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/HttpContextUtil.cs
Labels: backend, frontend, 491-40168674

#518 Add button to hide/show each reply message
  App/src/pages/dossier/DossierReview.tsx
Labels: frontend, reviewal, task

#528 Implement reset password email page
  App/package-lock.json
  App/src/App.tsx
  App/src/constants.ts
  App/src/pages/EmailResetPassword.tsx
  App/src/pages/Login.tsx
  App/src/services/user.ts
Labels: frontend, general, task

#531 added back button and page load on top
  App/src/pages/courseGroupings/CreateCourseGrouping.tsx
Labels: frontend, task, dossiers

#536 Post documentation for iteration 12
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, task

#532 Fix for 491 Daniel
  App/src/pages/EditProfileInfo.tsx
Labels: 491-40168674

#481 Added SearchGroupingsWithDossier
  Server/ConcordiaCurriculumManager/ConcordiaCurriculumManager.csproj
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseGroupingServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend

#541 Fix race condition on DbContext object
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
Labels: bug, backend, reviewal

#546 #499 add frontend voting feature
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierReview.tsx
  App/src/services/dossierreview.ts
Labels: frontend, reviewal, task, 491-40114180

#547 #501 add vote cache
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/DossierReview/DiscussionMessage.cs
  Server/ConcordiaCurriculumManager/Program.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CacheService.cs
  Server/ConcordiaCurriculumManager/Services/DossierReviewService.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CacheServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierReviewServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/DossierServiceTest.cs
Labels: backend, reviewal, task, dossiers, 491-40114180

#550 #549 implement course course grouping history
  Server/ConcordiaCurriculumManager/Controllers/CourseController.cs
  Server/ConcordiaCurriculumManager/Controllers/CourseGroupingController.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseGroupingRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/CourseRepository.cs
  Server/ConcordiaCurriculumManager/Repositories/DossierRepository.cs
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManager/Services/DossierService.cs
Labels: backend, reviewal, task, courses

#516 491- Roger | Implement Tree Structure Visualization for Course Groupings
  App/.eslintrc.cjs
  App/__tests__/__mocks__/testSetup.js
  App/jest.config.ts
  App/package-lock.json
  App/package.json
  App/src/components/CourseGrouping/CourseGroupingTreeStructure.tsx
  App/src/components/CourseGrouping/NodeElement.tsx
  App/src/pages/courseGroupings/CourseGrouping.tsx
Labels: frontend, 491-40177472

#558 Remove duplicate subgroupings
  Server/ConcordiaCurriculumManager/Services/CourseGroupingService.cs
Labels: bug, backend, curriculum

#556 Feature/tree user groups/#555
  App/src/components/CourseGrouping/CourseGroupingComponent.tsx
  App/src/components/GroupNodeElement.tsx
  App/src/components/ManageableGroupsTreeStructure.tsx
  App/src/pages/CoursesLeft.tsx
  App/src/pages/Directories.tsx
  App/src/pages/groups/ManageableGroups.tsx
  App/src/shared/Header.tsx
Labels: frontend, task, 491-40153034

#554 Implement reset password endpoint
  Server/ConcordiaCurriculumManager/Controllers/UsersController.cs
  Server/ConcordiaCurriculumManager/DTO/EmailPasswordResetDTO.cs
  Server/ConcordiaCurriculumManager/DTO/PasswordResetDTO.cs
  Server/ConcordiaCurriculumManager/Repositories/UserRepository.cs
  Server/ConcordiaCurriculumManager/Services/UserService.cs
  Server/ConcordiaCurriculumManagerTest/IntegrationTests/Repositories/UserRepositoryTests.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Controller/UsersControllerTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/UserServiceTest.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/UtilityFunctions/TestData.cs
Labels: backend, general, task

#552 #551 Allow course deletion after course group modification
  Server/ConcordiaCurriculumManager/Services/CourseService.cs
  Server/ConcordiaCurriculumManagerTest/UnitTests/Services/CourseServiceTest.cs
Labels: backend, courses

#553 Implement frontend for deleting review messages
  App/src/models/dossier.ts
  App/src/pages/dossier/DossierReview.tsx
  App/src/services/dossierreview.ts
  Server/ConcordiaCurriculumManager/Models/Curriculum/Dossiers/DossierReview/DiscussionMessage.cs
Labels: frontend, reviewal, task

#560 Fix bug where the "Dossiers Requiring Your Review" table still displays the dossier after performing a reviewal action
  App/src/pages/dossier/DossierToReview.tsx
Labels: bug, frontend, reviewal

#565 swapped search endpoinds
  App/src/components/CourseGrouping/SearchCourseGrouping.tsx
  App/src/pages/courseGroupings/CreateCourseGrouping.tsx
  App/src/pages/dossier/DossierDetails.tsx
  App/src/services/courseGrouping.ts
Labels: frontend, task, dossiers

#561 Feature/web scraper/403
  README.md
  Scraper/GeneratedCourseGroupings/aeroCourseGroupings.json
  Scraper/GeneratedCourseGroupings/buildCourseGroupings.json
  Scraper/GeneratedCourseGroupings/civilCourseGroupings.json
  Scraper/GeneratedCourseGroupings/compCourseGroupings.json
  Scraper/GeneratedCourseGroupings/elecCourseGroupings.json
  Scraper/GeneratedCourseGroupings/mechCourseGroupings.json
  Scraper/GeneratedCourseGroupings/softCourseGroupings.json
  Scraper/README.md
  Scraper/scraper.py
  Seeder/src/data/CourseGroupings.json
Labels: curriculum, courses

#575 #574 Post documentation for SOEN 491
  CourseAdmin/MilestonesDocument.txt
Labels: documentation, task

#538 RememberMe #537
  App/src/App.tsx
  App/src/pages/Login.tsx
  App/src/pages/Register.tsx
  App/src/services/auth.ts
Labels: frontend, general

#576 Fix bug where message replies automatically hide
  App/src/pages/dossier/DossierReview.tsx
Labels: bug, frontend, reviewal

#568 Refactor/stylefixes/#564
  App/src/App.tsx
  App/src/components/CourseGrouping/CourseGroupingTreeStructure.tsx
  App/src/components/ManageableGroupsTreeStructure.tsx
  App/src/constants.ts
  App/src/pages/BrowserList.tsx
  App/src/pages/courses/AddCourse.tsx
  App/src/pages/courses/CourseBrowser.tsx
  App/src/pages/courses/CourseBySubjectBrowser.tsx
  App/src/pages/courses/CourseDetails.tsx
  App/src/pages/courses/DeleteCourse.tsx
  App/src/pages/courses/DeleteCourseEdit.tsx
  App/src/pages/courses/EditCourse.tsx
Labels: frontend, task, refactoring

#539 Added Diff viewer to the Course Grouping Modification Requests
  App/src/components/CourseDifference/CourseGroupingDifference.tsx
  App/src/models/courseGrouping.ts
  App/src/pages/courseGroupings/CreateCourseGrouping.tsx
Labels: frontend, curriculum
